<LoginPage>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Username"
            size_hint: .25,.1
        Label:
            text: "Password"
            size_hint: .25,.1
        TextInput:
            id: username
            hint_text: "username"
        TextInput:
            id: password
            hint_text: "password"
        Button:
            text: "Enter"